#!/usr/bin/env bash

deploy=false
uglify=false

while (( $# > 1 )); do
  case $1 in
    -d|--deploy)
      deploy="$2"
      ;;
    -u|--uglify)
      uglify="$2"
      ;;
    *)
      break
      ;;
  esac
  shift 2 #shift positional argument $# by 2 
done

$deploy && echo "will deploy... deploy = $deploy"
$uglify && echo "will uglify... uglify = $uglify"
